INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_WRITINGGNURADIOBLOCKS WritingGNURadioBlocks)

FIND_PATH(
    WRITINGGNURADIOBLOCKS_INCLUDE_DIRS
    NAMES WritingGNURadioBlocks/api.h
    HINTS $ENV{WRITINGGNURADIOBLOCKS_DIR}/include
        ${PC_WRITINGGNURADIOBLOCKS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    WRITINGGNURADIOBLOCKS_LIBRARIES
    NAMES gnuradio-WritingGNURadioBlocks
    HINTS $ENV{WRITINGGNURADIOBLOCKS_DIR}/lib
        ${PC_WRITINGGNURADIOBLOCKS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/WritingGNURadioBlocksTarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(WRITINGGNURADIOBLOCKS DEFAULT_MSG WRITINGGNURADIOBLOCKS_LIBRARIES WRITINGGNURADIOBLOCKS_INCLUDE_DIRS)
MARK_AS_ADVANCED(WRITINGGNURADIOBLOCKS_LIBRARIES WRITINGGNURADIOBLOCKS_INCLUDE_DIRS)
